### ISSUE TITLE
tmp['fileExists'] not set

### ISSUE THREAD

**Issue by boverby** [bkbilly/Hikvision-Site#2]
Like the interface, but I think you must have further versions past this. There are variables in libHikvision.php that are unassigned, resulting in no events being displayed in time line.

I see on line 247 you unpack the key existByte

later on line 260, you refer to two unassigned variables , existByte1 and existByte2 , I'm guessing they are the two bytes in existByte.

When I forced the value of ` tmp['fileExists'] = True `after line 262, I started seeing events.

for reference only, my hikvision firmware is  `V5.4.5 build 170123`

**Comment by bkbilly** [comment]
I noticed this some weeks ago, but I never fixed it on github.
There is an issue with the events because it can get the events that have been deleted which are really old. I thought that the existByte are the ones that can check if the file has been deleted, but apparently I was wrong.
At the next commit I will remove this check.

**Comment by boverby** [comment]
Thanks for the confirmation,
Change of subject: any idea how to safely delete segments with a write to index00.bin or an api call?   I was considering trying to offline a tensorflow check to remove cloud/tree movement recordings. It would be interesting to "curate" or remove empty recordings without trying to completely re-produce the internal motion detection workflow.

**Comment by bkbilly** [comment]
It is a very good idea to implement something like that, though PHP is not the best way to do it. I have implemented the same library on Python which is much faster. You can check it [here](https://github.com/bkbilly/libHikvision).
If I were to do that, I would read the whole index00.bin file and ignore the files that I want to delete and save it again. With this method you might get into some problems because a new recording might appear before you replace the file but there might be ways around that.
If you think of anything please let me know because it is very interesting.

**Comment by bkbilly** [comment]
I know it's been a long time, but I forgot to fix the issue. I uploaded the changes and I consider this fixed.
